name: "Setup NextShell Environment"
description: "Sets up development environment for NextShell"
inputs:
  github-token:
    description: "GitHub token. You can pass secrets.GITHUB_TOKEN"
    required: true
  node-version:
    description: Node version
    required: false

runs:
  using: "composite"
  steps:
    - name: "Setup Rust"
      uses: ./.github/actions/setup-rust
      with:
        shared-cache-key: nextshell-debug-build
        cache-key: ${{ inputs.target }}
        save-cache: true
        github-token: ${{ inputs.github-token }}

    - name: "Setup capnproto"
      uses: ./.github/actions/setup-capnproto